package com.dkorduban.gridness.fixture;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Loads a text-format layout fixture (raster '.txt' + buildings '.buildings.txt')
 * generated by scripts/generate_fixtures.py. Java does not duplicate the
 * synthetic generators — fixtures are produced once by the Python script and
 * checked in to {@code data/fixtures/}.
 */
public final class LayoutFixture {

    public final String name;
    public final boolean[][] raster;  // [H][W]
    public final int width;
    public final int height;
    public final String expected;
    /** One entry per logical building; each is the list of wall cells {x, y}. */
    public final List<int[][]> buildings;

    public LayoutFixture(String name, boolean[][] raster, String expected, List<int[][]> buildings) {
        this.name = name;
        this.raster = raster;
        this.height = raster.length;
        this.width = raster[0].length;
        this.expected = expected;
        this.buildings = buildings;
    }

    public static LayoutFixture load(Path dir, String name) throws IOException {
        Path rasterPath = dir.resolve(name + ".txt");
        Path buildingsPath = dir.resolve(name + ".buildings.txt");
        Map<String, String> meta = new HashMap<>();
        boolean[][] raster = loadRaster(rasterPath, meta);
        List<int[][]> buildings = loadBuildings(buildingsPath);
        return new LayoutFixture(meta.getOrDefault("name", name), raster,
                meta.getOrDefault("expected", ""), buildings);
    }

    /** Default location for fixtures, resolved relative to the gradle project's parent. */
    public static Path defaultDir() {
        // Project layout: <repo>/java/{src,build,...} ; fixtures live in <repo>/data/fixtures
        Path here = Path.of("").toAbsolutePath();
        Path candidate = here.resolve("../data/fixtures").normalize();
        if (Files.isDirectory(candidate)) return candidate;
        // Tests sometimes get invoked from <repo> directly.
        Path alt = here.resolve("data/fixtures").normalize();
        if (Files.isDirectory(alt)) return alt;
        // Walk up looking for a 'data/fixtures' sibling.
        for (Path p = here; p != null; p = p.getParent()) {
            Path try1 = p.resolve("data/fixtures");
            if (Files.isDirectory(try1)) return try1;
        }
        return candidate;
    }

    private static boolean[][] loadRaster(Path path, Map<String, String> meta) throws IOException {
        List<String> rows = new ArrayList<>();
        int width = 0;
        for (String raw : Files.readAllLines(path)) {
            if (raw.startsWith(";")) {
                String body = raw.substring(1).trim();
                for (String tok : body.split("\\s+")) {
                    int eq = tok.indexOf('=');
                    if (eq > 0) meta.put(tok.substring(0, eq), tok.substring(eq + 1));
                }
                continue;
            }
            if (raw.isBlank()) continue;
            rows.add(raw);
            if (raw.length() > width) width = raw.length();
        }
        if (rows.isEmpty()) throw new IOException("empty raster file: " + path);
        boolean[][] out = new boolean[rows.size()][width];
        for (int y = 0; y < rows.size(); y++) {
            String row = rows.get(y);
            for (int x = 0; x < row.length(); x++) {
                if (row.charAt(x) == '#') out[y][x] = true;
            }
        }
        return out;
    }

    private static List<int[][]> loadBuildings(Path path) throws IOException {
        List<int[][]> buildings = new ArrayList<>();
        if (!Files.exists(path)) return buildings;
        for (String raw : Files.readAllLines(path)) {
            String line = raw.trim();
            if (line.isEmpty()) continue;
            String[] tokens = line.split("\\s+");
            int[][] cells = new int[tokens.length][2];
            for (int i = 0; i < tokens.length; i++) {
                int comma = tokens[i].indexOf(',');
                cells[i][0] = Integer.parseInt(tokens[i], 0, comma, 10);
                cells[i][1] = Integer.parseInt(tokens[i], comma + 1, tokens[i].length(), 10);
            }
            buildings.add(cells);
        }
        return buildings;
    }
}
